# Generated by Django 5.1.7 on 2025-03-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trucker", "0003_remove_driver_carrier_driver_carriers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dutystatus",
            name="location",
        ),
        migrations.AddField(
            model_name="dutystatus",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dutystatus",
            name="location_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dutystatus",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
