# Generated by Django 5.1.3 on 2025-03-15 20:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trucker", "0004_remove_dutystatus_location_dutystatus_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CycleCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calculation_date", models.DateField()),
                ("total_hours", models.FloatField()),
                ("cycle_type", models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name="dutystatus",
            options={"ordering": ["start_time"]},
        ),
        migrations.RenameField(
            model_name="dutystatus",
            old_name="latitude",
            new_name="location_lat",
        ),
        migrations.RenameField(
            model_name="dutystatus",
            old_name="longitude",
            new_name="location_lon",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="address",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="carriers",
        ),
        migrations.RemoveField(
            model_name="dutystatus",
            name="status_type",
        ),
        migrations.RemoveField(
            model_name="logentry",
            name="total_miles_driven",
        ),
        migrations.AddField(
            model_name="carrier",
            name="hos_cycle_choice",
            field=models.CharField(
                choices=[("60", "60-hour/7-day"), ("70", "70-hour/8-day")],
                default="70",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="carrier",
            name="mc_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trucker.carrier",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="current_cycle_used",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="driver",
            name="last_34hr_restart",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dutystatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("OFF", "Off Duty"),
                    ("SB", "Sleeper Berth"),
                    ("D", "Driving"),
                    ("ON", "On Duty (Not Driving)"),
                ],
                default="OFF",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="logentry",
            name="adverse_conditions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="logentry",
            name="duty_window_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="duty_window_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="total_miles",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trucker.carrier",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="home_terminal_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carrier",
            name="main_office_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dutystatus",
            name="location_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="trucker.driver",
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="trailer_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="truck_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name="dutystatus",
            index=models.Index(
                fields=["log_entry", "start_time"],
                name="trucker_dut_log_ent_1e18f0_idx",
            ),
        ),
        migrations.AddField(
            model_name="cyclecalculation",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trucker.driver"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cyclecalculation",
            unique_together={("driver", "calculation_date")},
        ),
    ]
