# Generated by Django 5.1.7 on 2025-03-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trucker", "0005_cyclecalculation_alter_dutystatus_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logentry",
            name="duty_window_end",
        ),
        migrations.RemoveField(
            model_name="logentry",
            name="duty_window_start",
        ),
        migrations.AddConstraint(
            model_name="logentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_odometer__gte", models.F("start_odometer"))),
                name="end_odometer_gte_start",
            ),
        ),
    ]
