# Generated by Django 5.1.7 on 2025-03-26 12:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trucker", "0007_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="average_speed",
            field=models.FloatField(default=50),
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("FUEL", "Fuel Stop"),
                            ("REST", "Rest Break"),
                            ("LOAD", "Loading/Unloading"),
                        ],
                        max_length=10,
                    ),
                ),
                ("location_name", models.CharField(max_length=255)),
                ("location_lat", models.FloatField()),
                ("location_lon", models.FloatField()),
                ("scheduled_time", models.DateTimeField()),
                ("actual_time", models.DateTimeField(blank=True, null=True)),
                (
                    "duration",
                    models.DurationField(default=datetime.timedelta(seconds=1800)),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="trucker.trip",
                    ),
                ),
            ],
        ),
    ]
