# Generated by Django 5.1.7 on 2025-03-26 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trucker", "0009_trip_completed_trip_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trucker.vehicle",
            ),
        ),
    ]
