# Generated by Django 5.1.7 on 2025-03-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trucker", "0010_trip_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="location_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stop",
            name="location_lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
