# Generated by Django 5.1.7 on 2025-03-28 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trucker", "0011_alter_stop_location_lat_alter_stop_location_lon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stop",
            options={"ordering": ["scheduled_time"]},
        ),
        migrations.AlterField(
            model_name="trip",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trucker.vehicle",
            ),
        ),
        migrations.AddIndex(
            model_name="stop",
            index=models.Index(
                fields=["scheduled_time", "stop_type"],
                name="trucker_sto_schedul_3f0d8a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.UniqueConstraint(
                condition=models.Q(("completed", False)),
                fields=("driver",),
                name="unique_active_trip_per_driver",
            ),
        ),
    ]
