name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 3.10.116.8 >> ~/.ssh/known_hosts

      - name: Validate connection
        run: ssh ubuntu@3.10.116.8 "hostname"

      - name: Sync code
        run: |
          rsync -avz --delete \
            --exclude=.git \
            --exclude=.github \
            --exclude='__pycache__' \
            --exclude=staticfiles \
            --filter="protect .env" \
            ./ ubuntu@3.10.116.8:/home/ubuntu/tracker/

      - name: Create .env on server
        run: |
          ssh ubuntu@3.10.116.8 "cat <<EOF > /home/ubuntu/tracker/.env
          DJANGO_PRODUCTION=${{ secrets.DJANGO_PRODUCTION }}
          DATABASE_ENGINE=${{ secrets.DATABASE_ENGINE }}
          DATABASE_HOST=${{ secrets.DATABASE_HOST }}
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          DATABASE_USER=${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          DATABASE_PORT=${{ secrets.DATABASE_PORT }}
          DEBUG=${{ secrets.DEBUG }}
          EOF
          "
          # Secure the .env file so only ubuntu user can read/write it
          ssh ubuntu@3.10.116.8 "chmod 600 /home/ubuntu/tracker/.env"

      - name: Deploy containers
        run: |
          ssh ubuntu@3.10.116.8 "
            cd /home/ubuntu/tracker && \
            docker compose up --build -d
          "
