name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 3.10.116.8 >> ~/.ssh/known_hosts

      - name: Validate connection
        run: ssh ubuntu@3.10.116.8 "hostname"

      - name: Sync code
        run: |
          rsync -avz --delete \
            --exclude=.git \
            --exclude=.github \
            --filter="protect .env" \
            ./ ubuntu@3.10.116.8:/home/ubuntu/tracker/

      - name: Deploy containers
        run: |
          ssh ubuntu@3.10.116.8 "cd /home/ubuntu/tracker && docker compose up --build -d"
    
          